# CI name
name: Run linters and test

# The on key is used to define when
# the CI should be triggered, aka Event
on:
  # When someone push or merge a pull request
  # inside the main branch
  push:
    branches:
      - main
  # When someone create a pull request from
  # the main branch
  pull_request:
    branches:
      - main

# A job is a set of steps that execute on the same runner.
# The jobs can be run in parallel or sequentially and can
# have many steps.
# In this case, I created a single job with many steps
# since the configuration is pretty simple but
# I could have created a different structure using parallel jobs.
# Each job uses an own runner.
jobs:
  # Job name
  suite:
    # OS of the runner
    runs-on: ubuntu-latest

    # A step is an individual task that can run commands in a job
    # and share the same runner.
    # Each step can run a ready-to-use action or a bash command
    steps:
      # Runner meaningful name
      - name: Checkout
        # Ready-to-use action made by GH or third party
        # companies
        # We can recognize the GH actions from the third party
        # ones checking the name prefix.
        # `actions/` = GH
        # `something-else/` = third party
        # This is a GH ready-to-use action
        uses: actions/checkout@v2


      - name: Run ESLint
        # Run the lint custom NPM command that triggers the
        # ESLint linter check
        run: npm run lint

      - name: Run Test
        # Run the test:unit custom NPM command
        # that runs Jest
        run: npm run test --watchAll=false
